name: HardcorePlugin
main: se.fredsfursten.hardcoreplugin.HardcorePlugin
version: 0.1
author: vanbrayne
description: A Minecraft plugin for Eithon fixes
commands:
  hardcore:
    description: Handle special stuff for the hardcore world
    usage: /hardcore unban
    permission-message: You don't have <permission>
permissions:
  hardcore.*:
    description: Gives access to all hardcore commands
    default: op
    hardcore.unban: true
  hardcore.unban:
    description: Access to /hardcore unban command
    default: op
