name: HardcorePlugin
main: se.fredsfursten.hardcoreplugin.HardcorePlugin
version: 1.2
author: vanbrayne
description: A Minecraft plugin for Eithon fixes
commands:
  hardcore:
    description: Handle special stuff for the hardcore world
    usage: /hardcore ban | unban | list
    permission-message: You don't have <permission>
permissions:
  hardcore.*:
    description: Gives access to all hardcore commands
    default: op
    hardcore.ban: true
    hardcore.unban: true
    hardcore.list: true
  hardcore.ban:
    description: Access to /hardcore ban command
    default: op
  hardcore.unban:
    description: Access to /hardcore unban command
    default: op
  hardcore.list:
    description: Access to /hardcore unban command
    default: op
